export const SET_FILENAME = "SET_FILENAME"

export const SET_MENUVISIBLE = "SET_MENUVISIBLE"

export const SET_SETTINGVISIBLE = "SET_SETTINGVISIBLE"

export const SET_DEFAULTFONTSIZE = "SET_DEFAULTFONTSIZE"

export const SET_CURRENTBOOK = "SET_CURRENTBOOK"

export const SET_DEFAULTFONTFAMILY = "SET_DEFAULTFONTFAMILY"

export const SET_FONTFAMILYVISIBLE = "SET_FONTFAMILYVISIBLE"

export const SET_DEFAULTTHEME = "SET_DEFAULTTHEME"

export const SET_PROGRESS = "SET_PROGRESS"

export const SET_BOOKAVAILABLE = "SET_BOOKAVAILABLE"

export const SET_SECTION = "SET_SECTION"

export const SET_COVER = "SET_COVER"

export const SET_METADATA = "SET_METADATA"

export const SET_NAVIGATION = "SET_NAVIGATION"

export const SET_OFFSET = "SET_OFFSET"

export const SET_BOOKMASK = "SET_BOOKMASK"

export const SET_PAGELISTS = "SET_PAGELISTS"
