export const SET_FILENAME = "SET_FILENAME"

export const SET_MENUVISIBLE = "SET_MENUVISIBLE"

export const SET_SETTINGVISIBLE = "SET_SETTINGVISIBLE"

export const SET_DEFAULTFONTSIZE = "SET_DEFAULTFONTSIZE"

export const SET_CURRENTBOOK = "SET_CURRENTBOOK"

export const SET_DEFAULTFONTFAMILY = "SET_DEFAULTFONTFAMILY"

export const SET_FONTFAMILYVISIBLE = "SET_FONTFAMILYVISIBLE"

export const SET_DEFAULTTHEME = "SET_DEFAULTTHEME"
