export const SET_HOTSEARCHOFFSET = "SET_HOTSEARCHOFFSET"

export const SET_FLAPCARDVISIBLE = "SET_FLAPCARDVISIBLE"

export const SET_ISEDIT_MODE = "SET_ISEDIT_MODE"

export const SET_SHELF_TITLE_VISIBLE = "SET_SHELF_TITLE_VISIBLE"

export const SET_SHELF_LIST = "SET_SHELF_LIST"

export const SET_SHELF_SELECTED = "SET_SHELF_SELECTED"

export const SET_SHELF_CATEGORY = "SET_SHELF_CATEGORY"

export const SET_CURRENTTYPE = "SET_CURRENTTYPE"
